
#games config list - list of games (what of series, name and indexpath)
#example:
#  - series: 'Series 1'
#    name: 'Game 1'
#    indexPath: 'gamefiles/1/begin.html'
games-cfg:
  games:
    - series: 'Series 1'
      name: 'Game 1'
      indexPath: 'gamefiles/1/begin.html'
      cardPath: 'cards/1.jpg'
    - series: 'Series 1'
      name: 'Game 2'
      indexPath: 'gamefiles/2/someName.html'
      cardPath: 'cards/2.jpg'
    - series: 'Series 1'
      name: 'Game 3'
      indexPath: 'gamefiles/3/someName.html'
      cardPath: 'cards/3.jpg'
    - series: 'Series 2'
      name: 'Game 4'
      indexPath: 'gamefiles/4/someName.html'
      cardPath: 'cards/4.jpg'
    - series: 'Series 2'
      name: 'Game 5'
      indexPath: 'gamefiles/5/someName.html'
      cardPath: 'cards/5.jpg'
    - series: 'Other'
      name: 'Game 6'
      indexPath: 'gamefiles/6/someName.html'
      cardPath: 'cards/6.jpg'
    - series: 'Series 7'
      name: 'Game 4'
      indexPath: 'gamefiles/7/someName.html'
      cardPath: 'cards/7.jpg'